# Generated by Django 4.2.1 on 2023-05-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0002_user_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('unitOfMeasure', models.CharField(max_length=4)),
                ('gardenNumber', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=100)),
                ('numOfPlants', models.IntegerField()),
                ('amountOfSun', models.CharField(max_length=15)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('datePlanted', models.DateField(null=True)),
                ('seedling', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.garden')),
            ],
        ),
        migrations.CreateModel(
            name='SeedJournal',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='GardenJournal',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('completed', models.TextField(blank=True)),
                ('todo', models.TextField(blank=True)),
                ('soilTemp', models.IntegerField(blank=True)),
                ('airTemp', models.IntegerField(blank=True)),
                ('weather', models.CharField(blank=True, max_length=150)),
                ('planted', models.TextField(blank=True)),
                ('observation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.user'),
        ),
    ]
