# Generated by Django 4.2.1 on 2023-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0003_garden_alter_user_email_alter_user_id_vegetable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenjournal',
            name='user',
        ),
        migrations.AlterField(
            model_name='gardenjournal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
